BOARD_SEPOLICY_DIRS += \
       device/samsung/msm8930-common/sepolicy/common \
       device/samsung/msm8930-common/sepolicy/device \
       device/samsung/msm8930-common/sepolicy/msm8960 \
       device/samsung/msm8930-common/sepolicy/test

BOARD_SEPOLICY_UNION += \
       adbd.te \
       adsprpcd.te \
       app.te \
       atfwd.te \
       audiod.te \
       bluetooth.te \
       bootanim.te \
       charger_monitor.te \
       cnd.te \
       debuggerd.te \
       device.te \
       dhcp.te \
       diag.te \
       diag_test.te \
       dnsmasq.te \
       domain.te \
       dpmd.te \
       drmserver.te \
       file_contexts \
       file.te \
       genfs_contexts \
       hbtp.te \
       healthd.te \
       hostapd.te \
       hvdcp.te \
       imscm.te \
       ims.te \
       init_shell.te \
       init.te \
       installd.te \
       install_recovery.te \
       insthk.te \
       ipacm.te \
       irsc_util.te \
       kernel.te \
       keystore.te \
       location_app.te \
       location.te \
       logd.te \
       mcStarter.te \
       mdm_helper.te \
       mediaserver.te \
       mediaserver_test.te \
       mmi.te \
       mm-pp-daemon.te \
       mm-qcamerad.te \
       mpdecision.te \
       msm_irqbalanced.te \
       netd.te \
       netmgrd.te \
       net.te \
       perfd.te \
       peripheral_manager.te \
       platform_app.te \
       port-bridge.te \
       property_contexts \
       property.te \
       qcomsysd.te \
       qlogd.te \
       qmi_ping.te \
       qmi_test_service.te \
       qmuxd.te \
       qseecomd.te \
       qti.te \
       radio.te \
       recovery.te \
       rfs_access.te \
       rild.te \
       rmt_storage.te \
       seapp_contexts \
       sectest.te \
       sensors.te \
       sensors_test.te \
       service_contexts \
       service.te \
       smd_test.te \
       ssr_diag.te \
       ssr_setup.te \
       subsystem_ramdump.te \
       surfaceflinger.te \
       sysinit.te \
       system_app.te \
       system_server.te \
       te_macros \
       thermald.te \
       thermal-engine.te \
       time_daemon.te \
       ueventd.te \
       uncrypt.te \
       untrusted_app.te \
       usb_uicc_daemon.te \
       usf.te \
       vm_bms.te \
       vold.te \
       wcnss_service.te \
       wfdservice.te \
       wpa.te \
       zygote.te
